common:
  project: KANDQN

training_args:
  seed: 42,43,44,45,46
  num_episodes: 300
  run_name: fast-kaqn-width_16_memory_50000
  agent: fkaqn
  use_cuda: False
  only_terminal_negative_reward: True
  agent_kwargs:
    batch_size: 128
    gamma: 0.99
    eps_start: 0.9
    eps_end: 0.05
    eps_decay: 1000
    tau: 0.005
    lr: 1.0e-04
    replay_memory_capacity: 50000
    width: 16
    grid: 8
