common:
  project: KANDQN

training_args:
  seed: 42,43,44,45,46,47,48,49,50,51
  num_episodes: 2000
  run_name: fast-kaqn-width_8-no-memory-10-seeds
  agent: fkaqn
  use_cuda: False
  only_terminal_negative_reward: True
  agent_kwargs:
    batch_size: 1
    gamma: 0.99
    eps_start: 0.9
    eps_end: 0.05
    eps_decay: 1000
    tau: 0.005
    lr: 1.0e-04
    replay_memory_capacity: 1
    width: 8
    grid: 8
