common:
  project: KANDQN

training_args:
  batch_size: 128
  gamma: 0.99
  eps_start: 0.9
  eps_end: 0.05
  eps_decay: 1000
  tau: 0.005
  lr: 1.0e-04
  replay_memory_capacity: 10000
  num_episodes: 600
  run_name: pytorch-episodes_600-refactored